#!/bin/zsh
# This hook is run after a new project is activated.
project=$(basename "$VIRTUAL_ENV")
mkdir -p ~/workspace/$project
tail -n 100 ~/.zshhistory > ~/workspace/$project/.zshhistory
tmx "$project"

